//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kyrsach.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Бронь
    {
        public long Код_бронирования { get; set; }
        public long Номер_номера { get; set; }
        public string Гость { get; set; }
        public Nullable<System.DateTime> Дата_заселения { get; set; }
        public Nullable<System.DateTime> Дата_выселения { get; set; }
        public Nullable<int> Кол_во_ночей { get; set; }
        public Nullable<decimal> Стоимость__в_день_ { get; set; }
        public Nullable<decimal> Итого { get; set; }
    
        public virtual Номера Номера { get; set; }
        public virtual Регистрация Регистрация { get; set; }
    }
}
