//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kyrsach.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Номера
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Номера()
        {
            this.Бронь = new HashSet<Бронь>();
            this.Статусы_номеров = new HashSet<Статусы_номеров>();
        }
    
        public long Номер { get; set; }
        public string Количество_комнат { get; set; }
        public string Количество_персон { get; set; }
        public decimal Стоимость_день_ { get; set; }
        public string Тип_номера { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Бронь> Бронь { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Статусы_номеров> Статусы_номеров { get; set; }
    }
}
