//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kyrsach.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Регистрация
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Регистрация()
        {
            this.Бронь = new HashSet<Бронь>();
        }
    
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string Паспорт { get; set; }
        public string Телефон { get; set; }
        public string Тип_номера { get; set; }
        public Nullable<System.DateTime> Дата_заселения { get; set; }
        public Nullable<System.DateTime> Дата_выселения { get; set; }
        public Nullable<decimal> Стоимость_в_день { get; set; }
        public Nullable<int> Кол_во_ночей { get; set; }
        public long Номер { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Бронь> Бронь { get; set; }
    }
}
